"""Глобавльное изменение бдшки

Revision ID: 6f814462fe86
Revises: f57af0b6c281
Create Date: 2025-05-03 20:00:09.093282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f814462fe86'
down_revision: Union[str, None] = 'f57af0b6c281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Сначала добавьте столбец как nullable
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Обновите все строки, установив значение по умолчанию для нового столбца
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")
    
    # Измените столбец, чтобы сделать его non-nullable
    op.alter_column('users', 'is_admin', nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
